#pragma config(Sensor, in1,    testSensor,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  testTouch,      sensorTouch)
#pragma config(Motor,  port1,           harvester_2,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left_drive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right_drive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           launch_motor_1, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           launch_motor_2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw_spin,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           left_lift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right_lift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw_lift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          harvester_1,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define sign(value) (value >= 0 ? 1 : -1)
#define controller_launch_forwards Btn5U
#define controller_launch_backwards Btn5D
#define controller_drive_left Ch2
#define controller_drive_right Ch3
#define controller_arm Ch1
#define controller_harvester_toggle Btn8D
#define controller_harvester2 Btn8D


float normalize_controller_input(float controller_input)
{
	float controller_sign = sign(controller_input);
	float new_input = controller_input * controller_sign;

	return new_input;
}

float get_power(float yAxis)
{
	float powers[6] = {0.0,0.3,0.5,0.7,1.0,1.0};
	float s = sign(yAxis);

	float y = abs(yAxis);

	int i = ((int)(y * 10.0))/2;

	if (i > 5) {
		return powers[5]*s;
		} else {
		return powers[i]*s;
	}
}

void set_launch_motor(float speed)
{
	int maximum_speed = speed > 0 ? 127 : 128;
	int motor_speed = maximum_speed * speed;
	motor[launch_motor_1] = motor_speed;
	motor[launch_motor_2] = motor_speed;
}

void set_left_drivetrain(float speed)
{
	int maximum_speed = speed > 0 ? 127 : 128;
	int motor_speed = maximum_speed * speed;
	motor[left_drive] = motor_speed;
	//motor[leftMotor2] = motor_speed;
}

void set_right_drivetrain(float speed)
{
	int maximum_speed = speed > 0 ? 127 : 128;
	int motor_speed = maximum_speed * speed;
	motor[right_drive] = motor_speed;
	//motor[rightMotor2] = motor_speed;
}


float get_joystick_axis(int index)
{
	float maximum_range = vexRT[index] > 0 ? -127.0 : -128.0;
	float joy_pos = (float)vexRT[index];
	return get_power(joy_pos / maximum_range);
}

float get_drive_left()
{
	return get_joystick_axis(controller_drive_left);
}

float get_drive_right()
{
	return get_joystick_axis(controller_drive_right);
}

float get_arm()
{
	return get_joystick_axis(controller_arm);
}

float get_potentiometer_degrees(int sensor)
{
	return 250.0 * (float)SensorValue[testSensor] / 4095.0;
}

bool harvester_running = false;
bool previous_harvester_button_state = false;
void harvester_update()
{
	int current_harvester_button_state = vexRT[controller_harvester_toggle];
	if(previous_harvester_button_state == true && current_harvester_button_state == false)
	{
		harvester_running = !harvester_running;
	}
}

task main()
{
	while(true)
	{
		harvester_update();

		if(harvester_running)
		{
			motor[harvester_1] = 127;
		}
		else
		{
			motor[harvester_1] = 0;
		}
		//getJoystickSettings(joystick);


		float speed_left = get_drive_left();
		set_left_drivetrain(speed_left);

		float speed_right = get_drive_right();
		set_right_drivetrain(speed_right);

		int test = SensorValue[testSensor];
		int test2 = SensorValue[testTouch];


		if(vexRT[controller_launch_forwards])
		{
			set_launch_motor(1.0);
		}
		else if(vexRT[controller_launch_backwards])
		{
			set_launch_motor(-1.0);
		}
		else
		{
			set_launch_motor(0.0);
		}



/*
		if(SensorValue[testTouch])
		{
			motor[testMotor] = 127;
		}
		else
		{
			motor[testMotor] = 0;
		}
*/
		//break;
	}
}
