#pragma config(Motor,  port1,           harvester_2,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left_drive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right_drive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           launch_motor_1, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           launch_motor_2, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw_roll,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           top_lift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottom_lift,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw_pitch,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          harvester_1,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LaunchForwards Btn5U
#define LaunchBackwards Btn5D
#define DriveLeft Ch3
#define DriveRight Ch2
#define ArmUp Btn6U
#define ArmDown Btn6D
#define HarvesterToggle Btn7UXmtr2
#define Harvester2 Btn7DXmtr2
#define ClawRotateLeft Btn8LXmtr2
#define ClawRotateRight Btn8RXmtr2
#define ClawPitchUp Btn8UXmtr2
#define ClawPitchDown Btn8DXmtr2

///////////Variables///////////
bool LastButtonState = false;
bool CurrentButtonState = false;

void SetLiftPower(int power){
	motor[top_lift] = power;
	motor[bottom_lift] = power;

}

task main()
{
	while(true)
	{
		////Assign Button///////
		bool BtnArmUp = (bool)vexRT[ArmUp];
		bool BtnArmDown = (bool)vexRT[ArmDown];
		bool BtnShooter = (bool)vexRT[LaunchForwards];



		//////ArmLift//////
		if (BtnArmUp){
			SetLiftPower(127);
		}
		else if (BtnArmDown){
			SetLiftPower(127);
		}
		else {
			SetLiftPower(0);
		}


		//////Shooter////////
		if (BtnShooter && !LastButtonState){
			CurrentButtonState = true;
		}

		if (CurrentButtonState != LastButtonState){
			LastButtonState = CurrentButtonState;

		}
		if (CurrentButtonState){
			motor[launch_motor_1] = 127;
			motor[launch_motor_2] = 127;
		}
		else {
			motor[launch_motor_1] = 0;
			motor[launch_motor_2] = 0;

		}

	}
}
