#pragma config(Motor,  port2,           _motor_,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define button_B Btn7D

bool buttonState = false;
bool LBS = false;
bool state = false;

task main()
{
	while (true){
    bool buttonState = (bool)(vexRT[button_B]);
		if (buttonState && !LBS){
			state = !state;
		}
		if (buttonState != LBS){
			LBS = buttonState;
		}
		if (state){
			motor[_motor_] = 127;

		}
		else {
			motor[_motor_] = 0;
		}

	}

}
