#pragma config(Motor,  port2,           _motor_,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HarvesterToggle Btn7UXmtr2

bool buttonState = false;
bool lastButtonState = false;
bool state = false;

task main()
{
	while (true){
    bool buttonState = (bool)(vexRT[HarvesterToggle]);
		if (buttonState && !lastButtonState){
			state = !state;
		}
		if (buttonState != lastButtonState){
			lastButtonState = buttonState;
		}
		if (state){
			motor[harvester_1] = 127;

		}
		else {
			motor[harvester_1] = 0;
		}

	}

}
